/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bgef.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import org.bgef.bsl.domains.Cartao;
import org.bgef.bsl.domains.Jogador;

/**
 *
 * @author MrFabio
 */
public class Cartoes extends javax.swing.JFrame {

    private ArrayList<Cartao> listacartoes;
    private ArrayList<Jogador> listajogadores;
    private Nova nova;
    private int idJogo;

    public Cartoes(List<Jogador> lista, Nova nova, int idJogo) {
        if (lista != null) {
            this.listajogadores = new ArrayList<>(lista);
        } else {
            this.listajogadores = new ArrayList<>();
        }
        this.listacartoes = new ArrayList<>();
        this.nova = nova;
        this.idJogo = idJogo;
        initComponents();
        DefaultComboBoxModel dcj = new DefaultComboBoxModel();
        jComboBoxJogadores.setModel(dcj);

        DefaultListModel dl1 = new DefaultListModel();
        jList1.setModel(dl1);
        DefaultListModel dl2 = new DefaultListModel();
        jList2.setModel(dl2);
        DefaultListModel dl3 = new DefaultListModel();
        jList3.setModel(dl3);

        for (Jogador j : listajogadores) {
            dcj.addElement(j);
        }
        this.setVisible(true);

    }

    public Cartoes() {
        this.listajogadores = new ArrayList<>();
        this.listacartoes = new ArrayList<>();

        initComponents();
    }

    public ArrayList<Cartao> getListacartoes() {
        return listacartoes;
    }

    public void setListacartoes(ArrayList<Cartao> listacartoes) {
        this.listacartoes = listacartoes;
    }

    public ArrayList<Jogador> getListajogadores() {
        return listajogadores;
    }

    public void setListajogadores(ArrayList<Jogador> listajogadores) {
        this.listajogadores = listajogadores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxJogadores = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxCartoes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButtonAddC = new javax.swing.JButton();
        jButtonInserir = new javax.swing.JButton();
        jButtonMenosAmarelos = new javax.swing.JButton();
        jButtonMenos2A = new javax.swing.JButton();
        jButtonMenosV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Cartões");

        jLabel2.setText("Jogador");

        jComboBoxCartoes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Amarelo", "Duplo Amarelo", "Vermelho" }));

        jLabel3.setText("Tipo de Cartão");

        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Amarelos");

        jLabel5.setText("Duplos Amarelos");

        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        jLabel6.setText("Vermelhos");

        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList3);

        jButtonAddC.setText(">");
        jButtonAddC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCActionPerformed(evt);
            }
        });

        jButtonInserir.setText("Atribuir");
        jButtonInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirActionPerformed(evt);
            }
        });

        jButtonMenosAmarelos.setText("-");
        jButtonMenosAmarelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosAmarelosActionPerformed(evt);
            }
        });

        jButtonMenos2A.setText("-");
        jButtonMenos2A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenos2AActionPerformed(evt);
            }
        });

        jButtonMenosV.setText("-");
        jButtonMenosV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMenosVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxCartoes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonAddC))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInserir)
                        .addGap(138, 138, 138)
                        .addComponent(jButtonMenosAmarelos)
                        .addGap(76, 76, 76)
                        .addComponent(jButtonMenos2A)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMenosV)
                        .addGap(47, 47, 47))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxCartoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonAddC)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInserir)
                    .addComponent(jButtonMenosAmarelos)
                    .addComponent(jButtonMenos2A)
                    .addComponent(jButtonMenosV))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCActionPerformed

        DefaultListModel dlmA = (DefaultListModel) jList1.getModel();
        DefaultListModel dlm2A = (DefaultListModel) jList2.getModel();
        DefaultListModel dlmV = (DefaultListModel) jList3.getModel();
        DefaultComboBoxModel dcJogadores = (DefaultComboBoxModel) jComboBoxJogadores.getModel();

        Jogador j = (Jogador) jComboBoxJogadores.getSelectedItem();

        if (((String) jComboBoxCartoes.getSelectedItem()).compareTo("Amarelo") == 0) {

            if (j != null) {
                dlmA.addElement(j);
                dcJogadores.removeElement(j);
            }

        } else if (((String) jComboBoxCartoes.getSelectedItem()).compareTo("Duplo Amarelo") == 0) {

            if (j != null) {
                dlm2A.addElement(j);
                dcJogadores.removeElement(j);
            }
        } else //vermelho
        {

            if (j != null) {
                dlmV.addElement(j);
                dcJogadores.removeElement(j);
            }
        }
    }//GEN-LAST:event_jButtonAddCActionPerformed

    private void jButtonMenosAmarelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosAmarelosActionPerformed

        DefaultListModel dlmA = (DefaultListModel) jList1.getModel();
        DefaultComboBoxModel dcJogadores = (DefaultComboBoxModel) jComboBoxJogadores.getModel();

        Jogador j = (Jogador) jList1.getSelectedValue();

        if (j != null) {
            dlmA.removeElement(j);
            dcJogadores.addElement(j);
        }
    }//GEN-LAST:event_jButtonMenosAmarelosActionPerformed

    private void jButtonMenos2AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenos2AActionPerformed
        DefaultListModel dlmwA = (DefaultListModel) jList2.getModel();
        DefaultComboBoxModel dcJogadores = (DefaultComboBoxModel) jComboBoxJogadores.getModel();

        Jogador j = (Jogador) jList2.getSelectedValue();

        if (j != null) {
            dlmwA.removeElement(j);
            dcJogadores.addElement(j);
        }
    }//GEN-LAST:event_jButtonMenos2AActionPerformed

    private void jButtonMenosVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMenosVActionPerformed
        DefaultListModel dlmV = (DefaultListModel) jList3.getModel();
        DefaultComboBoxModel dcJogadores = (DefaultComboBoxModel) jComboBoxJogadores.getModel();

        Jogador j = (Jogador) jList3.getSelectedValue();

        if (j != null) {
            dlmV.removeElement(j);
            dcJogadores.addElement(j);
        }
    }//GEN-LAST:event_jButtonMenosVActionPerformed

    private void jButtonInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirActionPerformed
        DefaultListModel dlmA = (DefaultListModel) jList1.getModel();
        DefaultListModel dlm2A = (DefaultListModel) jList2.getModel();
        DefaultListModel dlmV = (DefaultListModel) jList3.getModel();

        int sizea = dlmA.size();
        int size2a = dlm2A.size();
        int sizev = dlmV.size();

        for (int i = 0; i < sizea; i++) {
            Jogador j = (Jogador) dlmA.getElementAt(i);
            Cartao c = new Cartao(j.getId(), j, this.idJogo, "Amarelo");
            this.nova.addCartao(c);
        }

        for (int i = 0; i < size2a; i++) {
            Jogador j = (Jogador) dlm2A.getElementAt(i);
            Cartao c = new Cartao(j.getId(), j, this.idJogo, "Amarelo");
            Cartao c2 = new Cartao(j.getId(), j, this.idJogo, "Vermelho");
            this.nova.addCartao(c);
            this.nova.addCartao(c);
            this.nova.addCartao(c2);
        }

        for (int i = 0; i < sizev; i++) {
            Jogador j = (Jogador) dlmV.getElementAt(i);
            Cartao c = new Cartao(j.getId(), j, this.idJogo, "Vermelho");
            this.nova.addCartao(c);
        }

        dlmA.removeAllElements();
        dlm2A.removeAllElements();
        dlmV.removeAllElements();

        this.dispose();
    }//GEN-LAST:event_jButtonInserirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddC;
    private javax.swing.JButton jButtonInserir;
    private javax.swing.JButton jButtonMenos2A;
    private javax.swing.JButton jButtonMenosAmarelos;
    private javax.swing.JButton jButtonMenosV;
    private javax.swing.JComboBox jComboBoxCartoes;
    private javax.swing.JComboBox jComboBoxJogadores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
